---
- name: Install Grafana
  hosts: localhost
  become: yes
  
  tasks:
  - name: download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      state: present
      filename: grafana
  - name: Update apt cache and install grafana
    apt:
      name: grafana
      update_cache: yes
  # - name: Make sure grafana is started
  #   ansible.builtin.service:
  #     state: started
  #     enabled: true
  #     name: grafana-server
  #     use: sysvinit
  - name: Start Jenkins using service command
    ansible.builtin.command: service grafana-server start